### ISSUE TITLE
完善sentence管理界面的按钮功能

### ISSUE THREAD

**Issue by lutaoact** [genfengxue/clark#2]
1 删除知识点
API：/:id/delete_key/:keyId  PATCH（服务器端已经完成）
在这里删除，只是取消了和sentence之间的关联，知识点本身并不会删除。

2 新增知识点
API：/:id/new_key_point PATCH （服务器端已经完成）
会将知识点加入到key_point表中，然后再将_id加入到sentence里面完成关联

@bpceee 毕神，有空的时候，把这两个功能完善掉吧，多谢~~~

**Comment by bpceee** [comment]
新增知识点，是指新增一个已存在的知识点，还是不存在，需要新建？

**Comment by bpceee** [comment]
我打算学budweiser里添加课后作业的功能，加新习题和题库添加。
不要拦我，我要开始搬砖了！
